# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=6, max_digits=6)),
                ('supply', models.DecimalField(decimal_places=3, max_digits=12)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=12)),
                ('day_prc', models.FloatField(validators=[django.core.validators.MaxValueValidator(999.999), django.core.validators.MinValueValidator(0.0)])),
                ('hour_prc', models.FloatField(validators=[django.core.validators.MaxValueValidator(999.999), django.core.validators.MinValueValidator(0.0)])),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Coin',
            },
        ),
        migrations.CreateModel(
            name='Symbols',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Symbols',
            },
        ),
        migrations.AddField(
            model_name='coin',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Symbols'),
        ),
    ]
