# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Symbols',
            new_name='Symbol',
        ),
        migrations.AlterModelTable(
            name='symbol',
            table='Symbol',
        ),
    ]
