# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 12:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20170504_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='week_prc',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(999.999), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='coin',
            name='day_prc',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(999.999), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='coin',
            name='hour_prc',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(999.999), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
