# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20170504_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='coin',
            name='supply',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='coin',
            name='volume',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
