# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20170504_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Symbol', to_field='name'),
        ),
    ]
