# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_auto_20170504_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='name',
        ),
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='rest.Symbol'),
        ),
    ]
