# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_auto_20170507_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='coin',
            name='supply',
            field=models.DecimalField(decimal_places=3, max_digits=18),
        ),
        migrations.AlterField(
            model_name='coin',
            name='volume',
            field=models.DecimalField(decimal_places=3, max_digits=18),
        ),
    ]
