# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_auto_20170507_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='symbol',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
