# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_auto_20170507_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='update_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
